environments:
    - name: dev
      configs:
          endpoints:
              production: 
                url : 'https://dev.env.com:3000'
              sandbox: 
                url : 'https://dev.env.sand.com:3000'
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost
    - name: prod
      configs:
          endpoints:
              production: 
                url : 'https://prod.env.com:3080'
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Default
                deploymentVhost: localhost